//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalyticsText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyticsText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.AnalyticsText", typeof(AnalyticsText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматизирайте плащанията по сметките, за да избегнете такси за забавяне..
        /// </summary>
        public static string BillsTipFive {
            get {
                return ResourceManager.GetString("BillsTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потърсете промоционални цени и отстъпки..
        /// </summary>
        public static string BillsTipFour {
            get {
                return ResourceManager.GetString("BillsTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преговаряйте с доставчиците на услуги или преминете към по-бюджетни планове..
        /// </summary>
        public static string BillsTipOne {
            get {
                return ResourceManager.GetString("BillsTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглеждайте и коригирайте абонаментните услуги ежемесечно..
        /// </summary>
        public static string BillsTipThree {
            get {
                return ResourceManager.GetString("BillsTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете възможността за обединяване на услугите..
        /// </summary>
        public static string BillsTipTwo {
            get {
                return ResourceManager.GetString("BillsTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуализация на бюджет.
        /// </summary>
        public static string BudgetVisualization {
            get {
                return ResourceManager.GetString("BudgetVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходи по категории.
        /// </summary>
        public static string CategoryBased {
            get {
                return ResourceManager.GetString("CategoryBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверете за данъчни облекчения, свързани с разходите за грижи за деца..
        /// </summary>
        public static string ChildcareTipFive {
            get {
                return ResourceManager.GetString("ChildcareTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте предварително летните лагери и дейности..
        /// </summary>
        public static string ChildcareTipFour {
            get {
                return ResourceManager.GetString("ChildcareTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проучете местните програми за подпомагане на грижите за деца..
        /// </summary>
        public static string ChildcareTipOne {
            get {
                return ResourceManager.GetString("ChildcareTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разгледайте предоставяните от работодателя обезщетения за грижи за деца..
        /// </summary>
        public static string ChildcareTipThree {
            get {
                return ResourceManager.GetString("ChildcareTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помислете за споделяне на разходите с други семейства..
        /// </summary>
        public static string ChildcareTipTwo {
            get {
                return ResourceManager.GetString("ChildcareTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвестирайте в качествени артикули, които издържат по-дълго..
        /// </summary>
        public static string ClothingTipFive {
            get {
                return ResourceManager.GetString("ClothingTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете размяна на дрехи с приятели..
        /// </summary>
        public static string ClothingTipFour {
            get {
                return ResourceManager.GetString("ClothingTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купувайте сезонни дрехи по време на разпродажби..
        /// </summary>
        public static string ClothingTipOne {
            get {
                return ResourceManager.GetString("ClothingTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувайте по време на разпродажбите в края на сезона..
        /// </summary>
        public static string ClothingTipThree {
            get {
                return ResourceManager.GetString("ClothingTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложете стратегия за капсулен гардероб..
        /// </summary>
        public static string ClothingTipTwo {
            get {
                return ResourceManager.GetString("ClothingTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съвети за спестяване на разходи.
        /// </summary>
        public static string CostSavingTips {
            get {
                return ResourceManager.GetString("CostSavingTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте разходите за образование предварително..
        /// </summary>
        public static string EducationTipFive {
            get {
                return ResourceManager.GetString("EducationTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възползвайте се от образователните придобивки на работодателя..
        /// </summary>
        public static string EducationTipFour {
            get {
                return ResourceManager.GetString("EducationTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте безплатни онлайн образователни ресурси..
        /// </summary>
        public static string EducationTipOne {
            get {
                return ResourceManager.GetString("EducationTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете употребявани учебници или цифрови версии..
        /// </summary>
        public static string EducationTipThree {
            get {
                return ResourceManager.GetString("EducationTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидатствайте за стипендии и безвъзмездни средства..
        /// </summary>
        public static string EducationTipTwo {
            get {
                return ResourceManager.GetString("EducationTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте дейности в часовете извън пиковия период..
        /// </summary>
        public static string EntertainmentTipFive {
            get {
                return ResourceManager.GetString("EntertainmentTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възползвайте се от обществените съоръжения..
        /// </summary>
        public static string EntertainmentTipFour {
            get {
                return ResourceManager.GetString("EntertainmentTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потърсете безплатни събития или алтернативи с абонамент..
        /// </summary>
        public static string EntertainmentTipOne {
            get {
                return ResourceManager.GetString("EntertainmentTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Споделяйте стрийминг услуги с членовете на семейството..
        /// </summary>
        public static string EntertainmentTipThree {
            get {
                return ResourceManager.GetString("EntertainmentTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създавайте развлечения у дома..
        /// </summary>
        public static string EntertainmentTipTwo {
            get {
                return ResourceManager.GetString("EntertainmentTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходи.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансово сравнение.
        /// </summary>
        public static string FinancialComparison {
            get {
                return ResourceManager.GetString("FinancialComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансов отчет.
        /// </summary>
        public static string FinancialOverview {
            get {
                return ResourceManager.GetString("FinancialOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте купони и приложения за отстъпки за хранителни стоки..
        /// </summary>
        public static string FoodTipFive {
            get {
                return ResourceManager.GetString("FoodTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувайте по време на периоди на разпродажби..
        /// </summary>
        public static string FoodTipFour {
            get {
                return ResourceManager.GetString("FoodTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте храната предварително и намалете броя на вечерите навън..
        /// </summary>
        public static string FoodTipOne {
            get {
                return ResourceManager.GetString("FoodTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гответе у дома, вместо да поръчвате храна за вкъщи..
        /// </summary>
        public static string FoodTipThree {
            get {
                return ResourceManager.GetString("FoodTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купувайте съставки в насипно състояние, когато е възможно..
        /// </summary>
        public static string FoodTipTwo {
            get {
                return ResourceManager.GetString("FoodTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнявайте цените на различните доставчици на здравни услуги..
        /// </summary>
        public static string HealthcareTipFive {
            get {
                return ResourceManager.GetString("HealthcareTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете възможността за здравни спестовни сметки (HSA)..
        /// </summary>
        public static string HealthcareTipFour {
            get {
                return ResourceManager.GetString("HealthcareTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избирайте универсални лекарства, когато има такива..
        /// </summary>
        public static string HealthcareTipOne {
            get {
                return ResourceManager.GetString("HealthcareTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следете медицинските разходи за приспадане на данъци..
        /// </summary>
        public static string HealthcareTipThree {
            get {
                return ResourceManager.GetString("HealthcareTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посещавайте прегледи за профилактика..
        /// </summary>
        public static string HealthcareTipTwo {
            get {
                return ResourceManager.GetString("HealthcareTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувайте в магазините с намаления за основни стоки..
        /// </summary>
        public static string HouseholdSuppliesTipFive {
            get {
                return ResourceManager.GetString("HouseholdSuppliesTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддържайте инвентар, за да избегнете ненужни покупки..
        /// </summary>
        public static string HouseholdSuppliesTipFour {
            get {
                return ResourceManager.GetString("HouseholdSuppliesTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натрупайте средства по време на големи разпродажби..
        /// </summary>
        public static string HouseholdSuppliesTipOne {
            get {
                return ResourceManager.GetString("HouseholdSuppliesTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте продукти за многократна употреба, когато е възможно..
        /// </summary>
        public static string HouseholdSuppliesTipThree {
            get {
                return ResourceManager.GetString("HouseholdSuppliesTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купувайте консумативи в големи количества, когато е практично..
        /// </summary>
        public static string HouseholdSuppliesTipTwo {
            get {
                return ResourceManager.GetString("HouseholdSuppliesTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приход.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсете оферти от няколко доставчици..
        /// </summary>
        public static string InsuranceTipFive {
            get {
                return ResourceManager.GetString("InsuranceTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете възможности за групово застраховане чрез работодателите..
        /// </summary>
        public static string InsuranceTipFour {
            get {
                return ResourceManager.GetString("InsuranceTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когато е възможно, комбинирайте застрахователни полици..
        /// </summary>
        public static string InsuranceTipOne {
            get {
                return ResourceManager.GetString("InsuranceTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличете удръжките за по-ниски премии..
        /// </summary>
        public static string InsuranceTipThree {
            get {
                return ResourceManager.GetString("InsuranceTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглеждайте застраховките си всяка година, за да се уверите, че то е правилно защитено..
        /// </summary>
        public static string InsuranceTipTwo {
            get {
                return ResourceManager.GetString("InsuranceTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месец.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечно сравнение.
        /// </summary>
        public static string MonthlyComparison {
            get {
                return ResourceManager.GetString("MonthlyComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечна ставка на спестяванията.
        /// </summary>
        public static string MonthlySavingsRate {
            get {
                return ResourceManager.GetString("MonthlySavingsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нетна стойност.
        /// </summary>
        public static string NetWorth {
            get {
                return ResourceManager.GetString("NetWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма конкретни съвети..
        /// </summary>
        public static string NoTips {
            get {
                return ResourceManager.GetString("NoTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете въвеждането на „период на изчакване“ за импулсивни покупки..
        /// </summary>
        public static string OtherTipFive {
            get {
                return ResourceManager.GetString("OtherTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съхранявайте разписки за евентуални връщания или гаранции..
        /// </summary>
        public static string OtherTipFour {
            get {
                return ResourceManager.GetString("OtherTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документирайте неочакваните разходи за бъдещо планиране..
        /// </summary>
        public static string OtherTipOne {
            get {
                return ResourceManager.GetString("OtherTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редовно преглеждайте и категоризирайте некатегоризираните разходи..
        /// </summary>
        public static string OtherTipThree {
            get {
                return ResourceManager.GetString("OtherTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създайте фонд за непредвидени разходи..
        /// </summary>
        public static string OtherTipTwo {
            get {
                return ResourceManager.GetString("OtherTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напредък на фонда за спестяване.
        /// </summary>
        public static string SavingsGoalProgress {
            get {
                return ResourceManager.GetString("SavingsGoalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Степен на спестяване.
        /// </summary>
        public static string SavingsRate {
            get {
                return ResourceManager.GetString("SavingsRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглеждайте и коригирайте целите за спестяване на тримесечие..
        /// </summary>
        public static string SavingsTipFive {
            get {
                return ResourceManager.GetString("SavingsTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помислете за депозитни сертификати (CD)..
        /// </summary>
        public static string SavingsTipFour {
            get {
                return ResourceManager.GetString("SavingsTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройте автоматичен трансфер към спестовни сметки..
        /// </summary>
        public static string SavingsTipOne {
            get {
                return ResourceManager.GetString("SavingsTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възползвайте се от високодоходни спестовни сметки..
        /// </summary>
        public static string SavingsTipThree {
            get {
                return ResourceManager.GetString("SavingsTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте отделни сметки за различни цели..
        /// </summary>
        public static string SavingsTipTwo {
            get {
                return ResourceManager.GetString("SavingsTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-големи разходи по категории.
        /// </summary>
        public static string TopExpenses {
            get {
                return ResourceManager.GetString("TopExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обща нетна стойност.
        /// </summary>
        public static string TotalNetWorth {
            get {
                return ResourceManager.GetString("TotalNetWorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проследявайте горивната ефективност и оптимизирайте навиците си на шофиране..
        /// </summary>
        public static string TransportationTipFive {
            get {
                return ResourceManager.GetString("TransportationTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комбинирайте поръчките, за да намалите пътуванията..
        /// </summary>
        public static string TransportationTipFour {
            get {
                return ResourceManager.GetString("TransportationTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помислете за обществен транспорт, съвместно пътуване с кола или маршрути с по-нисък разход на гориво..
        /// </summary>
        public static string TransportationTipOne {
            get {
                return ResourceManager.GetString("TransportationTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проучете алтернативни методи за транспорт..
        /// </summary>
        public static string TransportationTipThree {
            get {
                return ResourceManager.GetString("TransportationTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редовно поддържайте автомобила си за по-добър пробег..
        /// </summary>
        public static string TransportationTipTwo {
            get {
                return ResourceManager.GetString("TransportationTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проучете безплатните атракции в дестинациите..
        /// </summary>
        public static string TravelTipFive {
            get {
                return ResourceManager.GetString("TravelTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опаковайте ефективно, за да избегнете такси за багаж..
        /// </summary>
        public static string TravelTipFour {
            get {
                return ResourceManager.GetString("TravelTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервирайте полети и хотели предварително.
        /// </summary>
        public static string TravelTipOne {
            get {
                return ResourceManager.GetString("TravelTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте стратегически кредитни карти с награди за пътуване..
        /// </summary>
        public static string TravelTipThree {
            get {
                return ResourceManager.GetString("TravelTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обмислете дати за пътуване извън сезона..
        /// </summary>
        public static string TravelTipTwo {
            get {
                return ResourceManager.GetString("TravelTipTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте одити на комуналните услуги, за да установите неефективността..
        /// </summary>
        public static string UtilitiesTipFive {
            get {
                return ResourceManager.GetString("UtilitiesTipFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преминете към LED осветление в цялото си пространство..
        /// </summary>
        public static string UtilitiesTipFour {
            get {
                return ResourceManager.GetString("UtilitiesTipFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използвайте енергийно ефективни уреди и изключвайте неизползваната електроника..
        /// </summary>
        public static string UtilitiesTipOne {
            get {
                return ResourceManager.GetString("UtilitiesTipOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отстранявайте своевременно течовете на вода, за да предотвратите разхищението им..
        /// </summary>
        public static string UtilitiesTipThree {
            get {
                return ResourceManager.GetString("UtilitiesTipThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инсталирайте интелигентни термостати за управление на температурата..
        /// </summary>
        public static string UtilitiesTipTwo {
            get {
                return ResourceManager.GetString("UtilitiesTipTwo", resourceCulture);
            }
        }
    }
}
