//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthenticationText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.AuthenticationText", typeof(AuthenticationText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате акаунт?.
        /// </summary>
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно към вход.
        /// </summary>
        public static string BackToLogin {
            get {
                return ResourceManager.GetString("BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на имейл адреса.
        /// </summary>
        public static string ChangeEmailButtonText {
            get {
                return ResourceManager.GetString("ChangeEmailButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на имейл адреса
        ///.
        /// </summary>
        public static string ChangeEmailTitle {
            get {
                return ResourceManager.GetString("ChangeEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смяна на паролата.
        /// </summary>
        public static string ChangePasswordButtonText {
            get {
                return ResourceManager.GetString("ChangePasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна на паролата.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, потвърдете новата си парола.
        ///.
        /// </summary>
        public static string ConfirmNewPasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете новата парола.
        /// </summary>
        public static string ConfirmNewPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете паролата.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдете паролата си.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете текущата си парола.
        ///.
        /// </summary>
        public static string CurrentPasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текуща парола
        ///.
        /// </summary>
        public static string CurrentPasswordLabel {
            get {
                return ResourceManager.GetString("CurrentPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не успяхте да промените имейла. Моля, опитайте отново..
        /// </summary>
        public static string EmailChangeFailed {
            get {
                return ResourceManager.GetString("EmailChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашият имейл и потребителско име бяха успешно променени. Моля, влезте отново..
        /// </summary>
        public static string EmailChangeSuccess {
            get {
                return ResourceManager.GetString("EmailChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е в невалиден формат.
        /// </summary>
        public static string EmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът е задължително поле.
        /// </summary>
        public static string EmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл или потребителско име.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола?.
        /// </summary>
        public static string ForgotPasswordButton {
            get {
                return ResourceManager.GetString("ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете имейл адреса си и ние ще ви изпратим инструкции за възстановяване на паролата.
        /// </summary>
        public static string ForgotPasswordSubtitle {
            get {
                return ResourceManager.GetString("ForgotPasswordSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата заявка беше успешна. Моля проверете имейл адреса си за линк за промяна на парола..
        /// </summary>
        public static string ForgotPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейлът или паролата не съвпадат.
        /// </summary>
        public static string InvalidLoginErrorMessage {
            get {
                return ResourceManager.GetString("InvalidLoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влезте в акаунта си, за да започнете приключението.
        /// </summary>
        public static string LoginSubtitle {
            get {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден имейл адрес..
        /// </summary>
        public static string NewEmailIsInvalidErrorMessage {
            get {
                return ResourceManager.GetString("NewEmailIsInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете новия си имейл адрес..
        /// </summary>
        public static string NewEmailIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NewEmailIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов имейл адрес.
        /// </summary>
        public static string NewEmailLabel {
            get {
                return ResourceManager.GetString("NewEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, въведете нова парола..
        /// </summary>
        public static string NewPasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NewPasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола
        ///.
        /// </summary>
        public static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов ли сте на платформата?.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стара Парола.
        /// </summary>
        public static string OldPasswordLabel {
            get {
                return ResourceManager.GetString("OldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опа! 😖 Търсеният URL адрес не беше намерен на този сървър..
        /// </summary>
        public static string PageNotFoundMessage {
            get {
                return ResourceManager.GetString("PageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницата не е намерена :(.
        /// </summary>
        public static string PageNotFoundTitle {
            get {
                return ResourceManager.GetString("PageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не успяхте да промените паролата. Моля, опитайте отново..
        /// </summary>
        public static string PasswordChangeFailed {
            get {
                return ResourceManager.GetString("PasswordChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата парола беше успешно променена. Моля, влезте отново..
        /// </summary>
        public static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдената парола не съвпада.
        /// </summary>
        public static string PasswordIsDifferentThanConfirmedErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsDifferentThanConfirmedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължително поле.
        /// </summary>
        public static string PasswordIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле за парола.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новата парола и потвърдената парола не съвпадат.
        ///.
        /// </summary>
        public static string PasswordsDoNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приключението започва тук 🚀.
        /// </summary>
        public static string RegisterSlogan {
            get {
                return ResourceManager.GetString("RegisterSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направете управлението на приложението лесно и забавно!.
        /// </summary>
        public static string RegisterSubtitle {
            get {
                return ResourceManager.GetString("RegisterSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вашата регистрация беше успешна. Използвайте данните си за да влезете в системата..
        /// </summary>
        public static string RegisterSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приключението започва тук 🚀.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смени паролата.
        /// </summary>
        public static string ResetPasswordButtonText {
            get {
                return ResourceManager.GetString("ResetPasswordButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нулиране на вашата парола.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпратете линк за възстановяване.
        /// </summary>
        public static string SendResetLinkButton {
            get {
                return ResourceManager.GetString("SendResetLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влез.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Влезте директно.
        /// </summary>
        public static string SignInInstead {
            get {
                return ResourceManager.GetString("SignInInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създайте акаунт.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профилът Ви е временно заключен.
        /// </summary>
        public static string UserLockedOutErrorMessage {
            get {
                return ResourceManager.GetString("UserLockedOutErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не успя да актуализирате потребителското име. Моля, опитайте отново..
        /// </summary>
        public static string UsernameChangeFailed {
            get {
                return ResourceManager.GetString("UsernameChangeFailed", resourceCulture);
            }
        }
    }
}
