//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BudgetText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.BudgetText", typeof(BudgetText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумата не може да бъде отрицателна.
        /// </summary>
        public static string AmountNegative {
            get {
                return ResourceManager.GetString("AmountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума.
        /// </summary>
        public static string BudgetAmount {
            get {
                return ResourceManager.GetString("BudgetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string BudgetCategory {
            get {
                return ResourceManager.GetString("BudgetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за бюджета.
        /// </summary>
        public static string BudgetDetails {
            get {
                return ResourceManager.GetString("BudgetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при запазването на бюджета..
        /// </summary>
        public static string BudgetError {
            get {
                return ResourceManager.GetString("BudgetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък от бюджети.
        /// </summary>
        public static string BudgetList {
            get {
                return ResourceManager.GetString("BudgetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месец.
        /// </summary>
        public static string BudgetMonth {
            get {
                return ResourceManager.GetString("BudgetMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при запазването на бюджета. Бюджетът не е намерен..
        /// </summary>
        public static string BudgetNotFound {
            get {
                return ResourceManager.GetString("BudgetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджети.
        /// </summary>
        public static string Budgets {
            get {
                return ResourceManager.GetString("Budgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджетът е добавен успешно!.
        /// </summary>
        public static string BudgetSuccess {
            get {
                return ResourceManager.GetString("BudgetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на бюджет.
        /// </summary>
        public static string DeleteBudget {
            get {
                return ResourceManager.GetString("DeleteBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени бюджет.
        /// </summary>
        public static string EditBudget {
            get {
                return ResourceManager.GetString("EditBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечният бюджет не може да бъде в бъдеще .
        /// </summary>
        public static string MonthFuture {
            get {
                return ResourceManager.GetString("MonthFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следващ.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предходен.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази бюджет.
        /// </summary>
        public static string SaveBudget {
            get {
                return ResourceManager.GetString("SaveBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запази промените.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задаване на бюджет.
        /// </summary>
        public static string SetBudget {
            get {
                return ResourceManager.GetString("SetBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете този бюджет?.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
