//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.DashboardText", typeof(DashboardText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акаунт.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки на акаунта.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на транзакция.
        /// </summary>
        public static string AddExpenses {
            get {
                return ResourceManager.GetString("AddExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителна информация.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анализи.
        /// </summary>
        public static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Известия.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баланс.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напомняния за сметки.
        /// </summary>
        public static string BillReminders {
            get {
                return ResourceManager.GetString("BillReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджетиране.
        /// </summary>
        public static string Budgeting {
            get {
                return ResourceManager.GetString("Budgeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на бюджета.
        /// </summary>
        public static string BudgetOverview {
            get {
                return ResourceManager.GetString("BudgetOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сравнение на разходите.
        /// </summary>
        public static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Табло.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документация.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък на транзакциите.
        /// </summary>
        public static string ExpenseList {
            get {
                return ResourceManager.GetString("ExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходи.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разходи тази седмица.
        /// </summary>
        public static string ExpensesThisWeek {
            get {
                return ResourceManager.GetString("ExpensesThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансово обобщение.
        /// </summary>
        public static string FinancialSummary {
            get {
                return ResourceManager.GetString("FinancialSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Храна.
        /// </summary>
        public static string Groceries {
            get {
                return ResourceManager.GetString("Groceries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приходи.
        /// </summary>
        public static string incomes {
            get {
                return ResourceManager.GetString("incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $39 по-малко от миналата седмица.
        /// </summary>
        public static string LessThanLastWeek {
            get {
                return ResourceManager.GetString("LessThanLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечни разходи.
        /// </summary>
        public static string MonthlyExpenses {
            get {
                return ResourceManager.GetString("MonthlyExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечен доход.
        /// </summary>
        public static string MonthlyIncome {
            get {
                return ResourceManager.GetString("MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 месеца.
        /// </summary>
        public static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моят профил.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма скорошни транзакции.
        /// </summary>
        public static string NoRecentTransactions {
            get {
                return ResourceManager.GetString("NoRecentTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация на известията.
        /// </summary>
        public static string NotificationConfig {
            get {
                return ResourceManager.GetString("NotificationConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпочитания за известия.
        /// </summary>
        public static string NotificationPreferences {
            get {
                return ResourceManager.GetString("NotificationPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спестявания.
        /// </summary>
        public static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полугодишен отчет.
        /// </summary>
        public static string SemiannualReport {
            get {
                return ResourceManager.GetString("SemiannualReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задаване на бюджет.
        /// </summary>
        public static string SetBudget {
            get {
                return ResourceManager.GetString("SetBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Останете на път и прегледайте последните си разходи..
        /// </summary>
        public static string StayOnTrack {
            get {
                return ResourceManager.GetString("StayOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общ баланс.
        /// </summary>
        public static string TotalBalance {
            get {
                return ResourceManager.GetString("TotalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление на транзакциите.
        /// </summary>
        public static string TransactionManagement {
            get {
                return ResourceManager.GetString("TransactionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string Utilities {
            get {
                return ResourceManager.GetString("Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добре дошъл отново, {0}!.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
    }
}
