//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LandingText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.LandingText", typeof(LandingText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проследявайте разходите си, задавайте бюджетни ограничения и постигайте финансовите си цели без усилия.
        /// Нашата система ви помага да сте на върха на финансите си с актуализации в реално време и проницателни отчети..
        /// </summary>
        public static string AboutSection {
            get {
                return ResourceManager.GetString("AboutSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За нас.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активни потребители.
        /// </summary>
        public static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашата система автоматично категоризира разходите ви и предоставя актуализации в реално време. Можете също така да добавяте разходи ръчно чрез таблото за управление..
        /// </summary>
        public static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да, можете да зададете месечни или годишни бюджетни лимити за различни категории. Нашата система ще ви предупреди, когато сте близо до превишаване на лимитите си..
        /// </summary>
        public static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете да разглеждате подробни финансови отчети и визуализации в раздел „Отчети“ на таблото за управление. Тези отчети ви помагат да разберете моделите на разходите си и да вземате информирани решения..
        /// </summary>
        public static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Използваме първокласни функции за сигурност и протоколи за криптиране, за да гарантираме, че финансовите ви данни са сигурни и защитени..
        /// </summary>
        public static string Answer4 {
            get {
                return ResourceManager.GetString("Answer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можете да се свържете с нашия екип за поддръжка чрез раздела „Поддръжка“ на таблото за управление или да ни изпратите имейл на support@zira.com. Ние сме тук, за да ви помогнем 24/7..
        /// </summary>
        public static string Answer5 {
            get {
                return ResourceManager.GetString("Answer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x носител на награда.
        /// </summary>
        public static string Awards1 {
            get {
                return ResourceManager.GetString("Awards1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6,5 хил. потребители.
        /// </summary>
        public static string Awards2 {
            get {
                return ResourceManager.GetString("Awards2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 хил. транзакции.
        /// </summary>
        public static string Awards3 {
            get {
                return ResourceManager.GetString("Awards3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6x препоръчан.
        /// </summary>
        public static string Awards4 {
            get {
                return ResourceManager.GetString("Awards4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Признат за отлични постижения.
        /// </summary>
        public static string AwardsDesc1 {
            get {
                return ResourceManager.GetString("AwardsDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управляващи бюджета си ежедневно.
        /// </summary>
        public static string AwardsDesc2 {
            get {
                return ResourceManager.GetString("AwardsDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проследявани месечно.
        /// </summary>
        public static string AwardsDesc3 {
            get {
                return ResourceManager.GetString("AwardsDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В най-добрите финансови блогове.
        /// </summary>
        public static string AwardsDesc4 {
            get {
                return ResourceManager.GetString("AwardsDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създадени бюджети.
        /// </summary>
        public static string BudgetsCreated {
            get {
                return ResourceManager.GetString("BudgetsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въпроси.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Намерете отговори на често задавани въпроси относно управлението на бюджета и използването на нашата система..
        /// </summary>
        public static string FAQDesc {
            get {
                return ResourceManager.GetString("FAQDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имате въпрос? Проверете често задаваните въпроси.
        /// </summary>
        public static string FAQTitle {
            get {
                return ResourceManager.GetString("FAQTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следете разходите си.
        /// </summary>
        public static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автоматично категоризиране на разходите..
        /// </summary>
        public static string Feature1Point1 {
            get {
                return ResourceManager.GetString("Feature1Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актуализации на разходите ви в реално време..
        /// </summary>
        public static string Feature1Point2 {
            get {
                return ResourceManager.GetString("Feature1Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробни отчети и визуализации..
        /// </summary>
        public static string Feature1Point3 {
            get {
                return ResourceManager.GetString("Feature1Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планирайте бюджета си.
        /// </summary>
        public static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюджетни категории с възможност за персонализиране..
        /// </summary>
        public static string Feature2Point1 {
            get {
                return ResourceManager.GetString("Feature2Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждения за бюджетни ограничения..
        /// </summary>
        public static string Feature2Point2 {
            get {
                return ResourceManager.GetString("Feature2Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месечно и годишно планиране на бюджета..
        /// </summary>
        public static string Feature2Point3 {
            get {
                return ResourceManager.GetString("Feature2Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаване на финансова информация.
        /// </summary>
        public static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изчерпателни финансови отчети..
        /// </summary>
        public static string Feature3Point1 {
            get {
                return ResourceManager.GetString("Feature3Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поглед към моделите на разходите..
        /// </summary>
        public static string Feature3Point2 {
            get {
                return ResourceManager.GetString("Feature3Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препоръки за финансово подобрение..
        /// </summary>
        public static string Feature3Point3 {
            get {
                return ResourceManager.GetString("Feature3Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проследяване на разходите.
        /// </summary>
        public static string FeatureBox1 {
            get {
                return ResourceManager.GetString("FeatureBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планиране на бюджета.
        /// </summary>
        public static string FeatureBox2 {
            get {
                return ResourceManager.GetString("FeatureBox2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансови анализи.
        /// </summary>
        public static string FeatureBox3 {
            get {
                return ResourceManager.GetString("FeatureBox3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни транзакции.
        /// </summary>
        public static string FeatureBox4 {
            get {
                return ResourceManager.GetString("FeatureBox4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наблюдавайте ежедневните си разходи и ги категоризирайте автоматично, за да следите навиците си за харчене..
        /// </summary>
        public static string FeatureBoxDesc1 {
            get {
                return ResourceManager.GetString("FeatureBoxDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задане на бюджетни лимити и финансови цели, с цел осигуряване, че се спазват правилата за разходите и спестяванията..
        /// </summary>
        public static string FeatureBoxDesc2 {
            get {
                return ResourceManager.GetString("FeatureBoxDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получете представа за финансовото си състояние с подробни отчети и визуализации на моделите на разходите ви..
        /// </summary>
        public static string FeatureBoxDesc3 {
            get {
                return ResourceManager.GetString("FeatureBoxDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уверете се, че финансовите ви данни са в безопасност с нашите първокласни функции за сигурност и протоколи за криптиране..
        /// </summary>
        public static string FeatureBoxDesc4 {
            get {
                return ResourceManager.GetString("FeatureBoxDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Водете си подробен отчет за навиците си на харчене и определете областите, в които можете да спестите..
        /// </summary>
        public static string FeatureDesc1 {
            get {
                return ResourceManager.GetString("FeatureDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определете бюджетни ограничения и цели, за да сте сигурни, че ще спазвате финансовите си планове..
        /// </summary>
        public static string FeatureDesc2 {
            get {
                return ResourceManager.GetString("FeatureDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вземайте информирани решения с подробна информация за финансовото си състояние..
        /// </summary>
        public static string FeatureDesc3 {
            get {
                return ResourceManager.GetString("FeatureDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Функции.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открийте мощните инструменти, които ви помагат да управлявате ефективно финансите си
        ///.
        /// </summary>
        public static string FeaturesDesc {
            get {
                return ResourceManager.GetString("FeaturesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финансови отчети.
        /// </summary>
        public static string FinancialAdvisors {
            get {
                return ResourceManager.GetString("FinancialAdvisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управляване на Вашите финанси.
        /// </summary>
        public static string ManagingYourFinances {
            get {
                return ResourceManager.GetString("ManagingYourFinances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как да следя разходите си?.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мога ли да задам лимити на бюджета си?.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как да прегледам финансовите отчети?.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли са финансовите ми данни?.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как мога да се свържа за помощ?.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Услуги.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запознайте се с набора от услуги, които предлагаме, за да ви помогнем да управлявате финансите си ефективно..
        /// </summary>
        public static string ServicesDesc {
            get {
                return ResourceManager.GetString("ServicesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поемете контрол върху.
        /// </summary>
        public static string TakeControl {
            get {
                return ResourceManager.GetString("TakeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия за ползване.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчетени транзакции.
        /// </summary>
        public static string TransactionsTracked {
            get {
                return ResourceManager.GetString("TransactionsTracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полезни ресурси.
        /// </summary>
        public static string UsefulLink {
            get {
                return ResourceManager.GetString("UsefulLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to с лекота.
        /// </summary>
        public static string WithEase {
            get {
                return ResourceManager.GetString("WithEase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to бюджета си.
        /// </summary>
        public static string YourBudget {
            get {
                return ResourceManager.GetString("YourBudget", resourceCulture);
            }
        }
    }
}
