//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SavingsGoalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SavingsGoalText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.SavingsGoalText", typeof(SavingsGoalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяване на нов фонд.
        /// </summary>
        public static string AddNewGoal {
            get {
                return ResourceManager.GetString("AddNewGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на фонд.
        /// </summary>
        public static string CreateGoal {
            get {
                return ResourceManager.GetString("CreateGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на нов спестовен фонд.
        /// </summary>
        public static string CreateSavingsGoal {
            get {
                return ResourceManager.GetString("CreateSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текуща сума.
        /// </summary>
        public static string CurrentAmount {
            get {
                return ResourceManager.GetString("CurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на целта за спестяване.
        /// </summary>
        public static string DeleteSavingsGoal {
            get {
                return ResourceManager.GetString("DeleteSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фонда на спестяване е изтрит успешно!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да изтриете фонда за спестяване: .
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактиране на целта за спестяване.
        /// </summary>
        public static string EditSavingsGoal {
            get {
                return ResourceManager.GetString("EditSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на фонд.
        /// </summary>
        public static string GoalName {
            get {
                return ResourceManager.GetString("GoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов спестовен фонд.
        /// </summary>
        public static string NewSavingsGoal {
            get {
                return ResourceManager.GetString("NewSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все още няма поставени цели за спестяване. Започнете да спестявате още днес!.
        /// </summary>
        public static string NoSavingsMessage {
            get {
                return ResourceManager.GetString("NoSavingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогрес.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запазване на промените.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спестовния фонд не е намерен.
        /// </summary>
        public static string SavingsGoalNotFound {
            get {
                return ResourceManager.GetString("SavingsGoalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спестовен фонд.
        /// </summary>
        public static string SavingsGoals {
            get {
                return ResourceManager.GetString("SavingsGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спестовния фонд е създаден успешно.
        /// </summary>
        public static string SavingsGoalSuccess {
            get {
                return ResourceManager.GetString("SavingsGoalSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева сума.
        /// </summary>
        public static string TargetAmount {
            get {
                return ResourceManager.GetString("TargetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева дата.
        /// </summary>
        public static string TargetDate {
            get {
                return ResourceManager.GetString("TargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фонда на спестяване е актуализиран успешно.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
