//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zira.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SavingsGoalText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SavingsGoalText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zira.Common.SavingsGoalText", typeof(SavingsGoalText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на фонд.
        /// </summary>
        public static string CreateGoal {
            get {
                return ResourceManager.GetString("CreateGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на нов спестовен фонд.
        /// </summary>
        public static string CreateSavingsGoal {
            get {
                return ResourceManager.GetString("CreateSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промяна.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име на фонд.
        /// </summary>
        public static string GoalName {
            get {
                return ResourceManager.GetString("GoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов спестовен фонд.
        /// </summary>
        public static string NewSavingsGoal {
            get {
                return ResourceManager.GetString("NewSavingsGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спестовен фонд.
        /// </summary>
        public static string SavingsGoals {
            get {
                return ResourceManager.GetString("SavingsGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева сума.
        /// </summary>
        public static string TargetAmount {
            get {
                return ResourceManager.GetString("TargetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Целева дата.
        /// </summary>
        public static string TargetDate {
            get {
                return ResourceManager.GetString("TargetDate", resourceCulture);
            }
        }
    }
}
